palapp/urls.py
from django.urls import path

from . import views
from .views import Inmoblistar, Jefelistar, Vendedorlistar, Clientelistar, Terrenolistar, Tramiteslistar, Notarialistar
from .views import Pagoslistar, Ventalistar, Bancoslistar, TipoDoclistar
from .views import UpdtInmobiliaria, UpdtCliente, UpdtJefe, UpdtVendedor, UpdtTerreno, UpdtTramite, UpdtNotaria
from .views import UpdtVenta, UpdtPagos, UpdtBanco, UpdtTipoDoc
from .views import InmobiliariaNuevo, InmobiliariaDetalle, JefeDetalle, VendedorDetalle, ClienteDetalle, TerrenoDetalle
from .views import TramitesDetalle, NotarioDetalle, VentaDetalle, gen_cron, ventasbulk, PagosDetalle
from .views import BancosDetalle, TipoDocDetalle, UpdtClientem, Pagosl


app_name = 'palapp'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # Inmobiliaria
    path('inmlist', Inmoblistar.as_view(template_name="palapp/inmlist.html"), name='inmlist'),
    path('padd', views.add_inmobiliaria, name='padd'),
    path('detalle/<int:pk>', InmobiliariaDetalle.as_view(template_name="palapp/detalle.html"), name='detalle'),
    path('editar/<int:pk>', UpdtInmobiliaria.as_view(template_name="palapp/editar.html"), name='editar'),

    # Jefe
    path('jeflist', Jefelistar.as_view(template_name="palapp/jeflist.html"), name='jeflist'),
    path('addjef', views.add_jefe, name='addjef'),
    path('detjef/<int:pk>', JefeDetalle.as_view(template_name="palapp/detjef.html"), name='detjef'),
    path('edtjef/<int:pk>', UpdtJefe.as_view(template_name="palapp/edtjef.html"), name='edtjef'),

    # Vendedor
    path('venlist', Vendedorlistar.as_view(template_name="palapp/venlist.html"), name='venlist'),
    path('addven', views.add_vendedor, name='addven'),
    path('detven/<int:pk>', VendedorDetalle.as_view(template_name="palapp/detven.html"), name='detven'),
    path('edtven/<int:pk>', UpdtVendedor.as_view(template_name="palapp/edtven.html"), name='edtven'),

    # Cliente
    path('clilist', Clientelistar.as_view(template_name="palapp/clilist.html"), name='clilist'),
    path('clilistm', Clientelistar.as_view(template_name="palapp/clilistm.html"), name='clilistm'),
    path('addcli', views.add_cliente, name='addcli'),
    path('detcli/<int:pk>', ClienteDetalle.as_view(template_name="palapp/detcli.html"), name='detcli'),
    path('edtcli/<int:pk>', UpdtCliente.as_view(template_name="palapp/edtcli.html"), name='edtcli'),
    path('edtclim/<int:pk>', UpdtClientem.as_view(template_name="palapp/edtclim.html"), name='edtclim'),

    # Terrenos
    path('terlist', Terrenolistar.as_view(template_name="palapp/terlist.html"), name='terlist'),
    path('addter', views.add_terreno, name='addter'),
    path('deter/<int:pk>', TerrenoDetalle.as_view(template_name="palapp/deter.html"), name='deter'),
    path('plano', Terrenolistar.as_view(template_name="palapp/plano.html"), name='plano'),
    path('detmap/<int:pk>', TerrenoDetalle.as_view(template_name="palapp/detmap.html"), name='detmap'),
    path('edtterr/<int:pk>', UpdtTerreno.as_view(template_name="palapp/edtterr.html"), name='edtterr'),

    # Gestion de ventas
    path('tralist', Tramiteslistar.as_view(template_name="palapp/tralist.html"), name='tralist'),
    path('addtra', views.add_tramites, name='addtra'),
    path('dettra/<int:pk>', TramitesDetalle.as_view(template_name="palapp/dettra.html"), name='dettra'),
    path('edttra/<int:pk>', UpdtTramite.as_view(template_name="palapp/edttra.html"), name='edttra'),

    # Notarias
    path('lisnot', Notarialistar.as_view(template_name="palapp/lisnot.html"), name='lisnot'),
    path('addnot', views.add_notaria, name='addnot'),
    path('detnot/<int:pk>', NotarioDetalle.as_view(template_name="palapp/detnot.html"), name='detnot'),
    path('edtnot/<int:pk>', UpdtNotaria.as_view(template_name="palapp/edtnot.html"), name='edtnot'),

    # Cierre de Venta
    path('lisvta', Ventalistar.as_view(template_name="palapp/lisvta.html"), name='lisvta'),
    path('addvta', views.add_venta, name='addvta'),
    path('detvta/<int:pk>', VentaDetalle.as_view(template_name="palapp/detvta.html"), name='detvta'),
    path('edtvta/<int:pk>', UpdtVenta.as_view(template_name="palapp/edtvta.html"), name='edtvta'),
    path('edtvta/cplan/<int:pk>', gen_cron, name='cplan'),
    # path('lisdpag/<int:pk>', PagosDetalle.as_view(template_name="palapp/lisdpag.html"), name='lisdpag')

    # Pagos x contrato
    path('lispag/<int:id>', views.Pagosl, name='lispag'),
    path('lispag/detpag/<int:pk>', PagosDetalle.as_view(template_name="palapp/detpag.html"), name='detpag'),
    path('lispag/edtpag/<int:pk>', UpdtPagos.as_view(template_name="palapp/edtpag.html"), name='edtpag'),

    # Pagos TODO
    path('lispagt/', Pagoslistar.as_view(template_name="palapp/lispagt.html"), name='lispagt'),
    path('addpag', views.add_pagos, name='addpag'),
    path('detpagt/<int:pk>', PagosDetalle.as_view(template_name="palapp/detpagt.html"), name='detpagt'),
    path('edtpagt/<int:pk>', UpdtPagos.as_view(template_name="palapp/edtpagt.html"), name='edtpagt'),

    # Bancos
    path('lisbco', Bancoslistar.as_view(template_name="palapp/lisbco.html"), name='lisbco'),
    path('addbco', views.add_bancos, name='addbco'),
    path('detbco/<int:pk>', BancosDetalle.as_view(template_name="palapp/detbco.html"), name='detbco'),
    path('edtbco/<int:pk>', UpdtBanco.as_view(template_name="palapp/edtbco.html"), name='edtbco'),

    # Tipos de Documento
    path('listdoc', TipoDoclistar.as_view(template_name="palapp/listdoc.html"), name='listdoc'),
    path('addtdoc', views.add_tipodoc, name='addtdoc'),
    path('dettdoc/<int:pk>', TipoDocDetalle.as_view(template_name="palapp/dettdoc.html"), name='dettdoc'),
    path('edttdoc/<int:pk>', UpdtTipoDoc.as_view(template_name="palapp/edttdoc.html"), name='edttdoc'),

    # Seguridad
    path('profile', views.Profile, name='profile'),
    path('change_password', views.Change_Password, name='change_password'),

    # Mostrar formulario de alta de nuevo registro///// sin uso


    path('nuevo', InmobiliariaNuevo.as_view(template_name='palapp/inmcrear.html'), name='nuevo'),

    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

palmarpr/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('palapp/', include('palapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

 ]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

palapp/views.py
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import AnonymousUser, User
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect, HttpRequest
from django.shortcuts import get_object_or_404, render
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy
from django.views import generic, View
from django.utils import timezone
from datetime import datetime, timedelta
from dateutil.relativedelta import *

from .models import Pagos


from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm

from django.contrib import messages

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from . models import Inmobiliaria, Question, Choice, Jefe, Vendedor, Cliente, Terreno, Tramites
from . models import Notaria, Pagos, Venta, Bancos, TipoDoc
from .forms import InmobiliariaForm, JefeForm, VendedorForm, ClienteForm, TerrenoForm, TramitesForm, NotariaForm
from .forms import VentaForm, PagosForm, BancosForm, TipoDocForm

def is_in_multiple_groups(user):
    return user.groups.filter(name__in=['administrador', 'responsable']).exists()


# Seccion Listar
# #########################################

class Inmoblistar(ListView):
    model = Inmobiliaria
    paginate_by = 8
    ordering = ['rassoc']

    def get_queryset(self):

        if self.request.GET.get('buscar') is not None:
            q=self.request.GET.get('buscar')

            return Inmobiliaria.objects.filter(Q(ruc__icontains=q) | Q(direccion__icontains=q) |
                                               Q(rassoc__icontains=q) | Q(correo__icontains=q) |
                                               Q(cel1__icontains=q))

        return super().get_queryset()


class Jefelistar(ListView):
    model = Jefe
    paginate_by = 8
    ordering = ['appat', 'apmat', 'nomb']


class Vendedorlistar(ListView):
    model = Vendedor
    paginate_by = 8
    ordering = ['appat', 'apmat', 'nomb']


class Clientelistar(ListView):
    model = Cliente
    paginate_by = 8
    ordering = ['appat', 'apmat', 'nomb']

    def get_queryset(self):
        if self.request.GET.get('buscar') is not None:
            q=self.request.GET.get('buscar')

            return Cliente.objects.filter(Q(dni__icontains=q) | Q(direccion__icontains=q) |
                                          Q(directra__icontains=q) | Q(correo__icontains=q) |
                                          Q(cel1__icontains=q) | Q(appat__icontains=q) |
                                          Q(apmat__icontains=q) | Q(nomb__icontains=q) |
                                          Q(percon__icontains=q) | Q(celcon__icontains=q) |
                                          Q(ocupacion__icontains=q))

        return super().get_queryset()


class Clientelistarm(ListView):
    model = Cliente
    paginate_by = 8
    ordering = ['appat', 'apmat', 'nomb']

    def get_queryset(self):
        if self.request.GET.get('buscar') is not None:
            q=self.request.GET.get('buscar')

            return Cliente.objects.filter(Q(dni__icontains=q) | Q(direccion__icontains=q) |
                                          Q(directra__icontains=q) | Q(correo__icontains=q) |
                                          Q(cel1__icontains=q) | Q(appat__icontains=q) |
                                          Q(apmat__icontains=q) | Q(nomb__icontains=q) |
                                          Q(percon__icontains=q) | Q(celcon__icontains=q) |
                                          Q(ocupacion__icontains=q))

        return super().get_queryset()


class Terrenolistar(ListView):
    model = Terreno
    paginate_by = 8
    ordering = ['estado', 'manzana', 'lote']

    def get_queryset(self):
        if self.request.GET.get('buscar') is not None:
            q=self.request.GET.get('buscar')

            return Terreno.objects.filter(Q(codigo__icontains=q) | Q(manzana__icontains=q) |
                                          Q(preciod__icontains=q) | Q(area__icontains=q) |
                                          Q(lfrente__icontains=q) | Q(lder__icontains=q) |
                                          Q(lizq__icontains=q) | Q(lfondo__icontains=q) |
                                          Q(norte__icontains=q) | Q(sur__icontains=q) |
                                          Q(este__icontains=q) | Q(oeste__icontains=q) |
                                          Q(observaciones__icontains=q))
        return super().get_queryset()


class Tramiteslistar(ListView):
    model = Tramites
    paginate_by = 8
    ordering = ['-fecha_creacion']

    def get_queryset(self):
        if is_in_multiple_groups(self.request.user):

            if self.request.GET.get('buscar') is not None:
                q = self.request.GET.get('buscar')

                return Tramites.objects.filter(Q(descrip__icontains=q) | Q(lugar__icontains=q) |
                                              Q(resultado__icontains=q) | Q(por_hacer__icontains=q) |
                                              Q(nivel__icontains=q) | Q(observ__icontains=q) |
                                              Q(fec_prox__icontains=q))
        else:
            if self.request.GET.get('buscar') is not None:
                q = self.request.GET.get('buscar')

                return Tramites.objects.filter((Q(descrip__icontains=q) | Q(lugar__icontains=q) |
                                               Q(resultado__icontains=q) | Q(por_hacer__icontains=q) |
                                               Q(nivel__icontains=q) | Q(observ__icontains=q) |
                                               Q(fec_prox__icontains=q)) & Q(usuario_crea=self.request.user))
            else:
                return Tramites.objects.filter(Q(usuario_crea=self.request.user))

        return super().get_queryset()


class Notarialistar(ListView):
    model = Notaria
    paginate_by = 8
    ordering = ['rassoc']


class Ventalistar(ListView):
    model = Venta
    paginate_by = 8
    ordering = ['-nro_cont']

    def get_queryset(self):
        if self.request.GET.get('buscar') is not None:
            q = self.request.GET.get('buscar')

            return Tramites.objects.filter(Q(nro_cont__icontains=q) | Q(cliente__icontains=q) |
                                           Q(fecha_con__icontains=q) | Q(terreno__icontains=q) |
                                           Q(vendedor__icontains=q) | Q(observ__icontains=q) |
                                           Q(banco__icontains=q) | Q(notaria__icontains=q) |
                                           Q(fec_con__icontains=q))
        return super().get_queryset()


def Pagosl(request, id):

    pagos = Pagos.objects.filter(venta=id)

    return render(request, 'palapp/lispag.html', {'pagos': pagos})


class Pagoslistar(ListView):
    model = Pagos
    paginate_by = 8
    ordering = ['fec_vcto']

    def get_queryset(self):
        fini = '1900-01-01'
        ffin = '2050-12-31'
        canc = 'P'
        if self.request.GET.get('fini') is not None:
            if len(self.request.GET.get('fini')) !=0:
                fini = self.request.GET.get('fini')
                fini = fini.replace("/", "-")
        if self.request.GET.get('ffin') is not None:
            if len(self.request.GET.get('ffin')) !=0:
                ffin = self.request.GET.get('ffin')
                ffin = ffin.replace("/", "-")
        if (self.request.GET.get('fini') is None and self.request.GET.get('ffin') is not None):
            if len(self.request.GET.get('fini')) == 0 and len(self.request.GET.get('ffin')) != 0:
                fini=ffin
        if (self.request.GET.get('fini') is not None and self.request.GET.get('ffin') is None):
            if len(self.request.GET.get('fini')) != 0 and len(self.request.GET.get('ffin')) == 0:
                ffin=fini
        if self.request.GET.get('lote') is not None:
            if len(self.request.GET.get('lote')) != 0:
                lote = self.request.GET.get('lote')
        if self.request.GET.get('canc') is not None:
            if len(self.request.GET.get('canc')) != 0:
               if self.request.GET.get('canc')=='Pendientes':
                   canc = 'P'
               else:
                   canc = 'C'
            else:
               canc = 'P'
   
        if self.request.GET.get('lote') is not None:
            if len(self.request.GET.get('lote')) != 0:
                return Pagos.objects.filter((Q(venta__terreno__codigo__icontains=lote) | Q(venta__cliente__appat__icontains=lote)) &
                                             Q(fec_vcto__range=(fini, ffin))).filter(estado=canc)
            else:
                return Pagos.objects.filter(Q(fec_vcto__range=(fini, ffin))).filter(estado=canc)

        return super().get_queryset()


class Bancoslistar(ListView):
    model = Bancos
    paginate_by = 8
    ordering = ['rassoc']


class TipoDoclistar(ListView):
    model = TipoDoc
    paginate_by = 8
    ordering = ['tipodoc']


# Para obtener todos los campos de un registro de la tablas

class InmobiliariaDetalle(DetailView):
    model = Inmobiliaria


class JefeDetalle(DetailView):
    model = Jefe


class VendedorDetalle(DetailView):
    model = Vendedor


class ClienteDetalle(DetailView):
    model = Cliente


class TerrenoDetalle(DetailView):
    model = Terreno


class TramitesDetalle(DetailView):
    model = Tramites


class NotarioDetalle(DetailView):
    model = Notaria


class BancosDetalle(DetailView):
    model = Bancos


class TipoDocDetalle(DetailView):
    model =  TipoDoc


class VentaDetalle(DetailView):
    model = Venta


class PagosDetalle(DetailView):
    model = Pagos


# Para insertar un nuevo contacto en la tabla Inmobiliaria
class InmobiliariaNuevo(SuccessMessageMixin, CreateView):
    model = Inmobiliaria

palapp/templates/palapp/addbco.html
{% extends "palapp/base.html" %}

 {% load static %} <!-- Cargar URL raíz -->

 {% load widget_tweaks %}

{% block content %}

<p style="background-color: green; color: #ffffff; font-weight: bold; font-size: x-large"> ENTIDADES FINANCIERAS </p>

<style>
    .cuerpo {
        margin-left: 40px;
        margin-right: 40px;
    }

</style>
<div id>
  <div class="cuerpo">

  <form action="{% url 'palapp:addbco' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

  <center>
  <button type="submit" class="btn btn-primary">Guardar Entidad</button>
  <a href="lisbco" type="submit" class="btn btn-primary">Cancelar</a>
  </center>

</form>
</div>
</div>




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

{% endblock %}

palapp/templates/palapp/addtdoc.html
{% extends "palapp/base.html" %}

 {% load static %} <!-- Cargar URL raíz -->

 {% load widget_tweaks %}

{% block content %}

<p style="background-color: green; color: #ffffff; font-weight: bold; font-size: x-large"> TIPOS DE DOCUMENTO </p>

<style>
    .cuerpo {
        margin-left: 40px;
        margin-right: 40px;
    }

</style>
<div id>
  <div class="cuerpo">

  <form action="{% url 'palapp:addtdoc' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

  <center>
  <button type="submit" class="btn btn-primary">Guardar Documento</button>
  <a href="listdoc" type="submit" class="btn btn-primary">Cancelar</a>
  </center>

</form>
</div>
</div>




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

{% endblock %}

palapp/templates/palapp/cplan.html
{% extends "palapp/base.html" %}

 {% load static %} <!-- Cargar URL raíz -->

 {% load widget_tweaks %}

{% block content %}

<center>
<p style="background-color: green; color: #ffffff; font-weight: bold; font-size: x-large"> PLAN DE PAGOS GENERADO EXITOSAMENTE</p>
</center>

<style>
    .cuerpo {
        margin-left: 40px;
        margin-right: 40px;
    }

</style>

<div>


<form method="post" enctype="multipart/form-data">
  <!-- Token de seguridad para poder crear un nuevo registro -->
  {% csrf_token %}

<table >

  <div class="form-group">
  </div>
    <div class="container">
            <div class="col-md-12 genera">
                <form method="get">
                        <div class="input-group col-md-12">
                            <table style="width:30%">
                            <p><span style="font-weight: bold;">Precio US%:</span> <br style="margin-left: 60px;"> {{form.preciod}}</p>
                            <p><span style="font-weight: bold;">Inicial:</span> <br style="margin-left: 60px;"> {{form.inicial}}</p>
                            <p><span style="font-weight: bold;">Cuotas:</span> <br style="margin-left: 60px;"> {{form.cuotas}}</p>
                            </table>
                        </div>
                </form>
            </div>
    </div>
</table>
    <center>
    <a href="{% url 'palapp:lisvta' %}" type="submit" class="btn btn-primary">RETORNA</a>
</center>
</form>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

{% endblock %}

palapp/templates/palapp/edtnot.html
{% extends "palapp/base.html" %}

 {% load static %} <!-- Cargar URL raíz -->

 {% load widget_tweaks %}

{% block content %}

<p style="background-color: green; color: #ffffff; font-weight: bold; font-size: x-large"> NOTARÍA </p>

<style>
    .cuerpo {
        margin-left: 40px;
        margin-right: 40px;
    }

</style>
<div id>
  <div class="cuerpo">

<form method="post" enctype="multipart/form-data">

  <!-- Token de seguridad para poder crear un nuevo registro -->
  {% csrf_token %}
<table style="width:100%">
  {{ form.as_table }}
</table>
<center>
  <button type="submit" class="btn btn-primary">Guardar</button>
  <a href="{% url 'palapp:lisnot' %}" type="submit" class="btn btn-primary">Cancelar</a>
</center>

</form>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</div>
{% endblock %}

palapp/templates/palapp/edtpagt.html
{% extends "palapp/base.html" %}

 {% load static %} <!-- Cargar URL raíz -->

 {% load widget_tweaks %}

{% block content %}

<p style="background-color: green; color: #ffffff; font-weight: bold; font-size: x-large"> PAGOS </p>

<style>
    .cuerpo {
        margin-left: 40px;
        margin-right: 40px;
    }

</style>
<div id>
  <div class="cuerpo">

<form method="post" enctype="multipart/form-data">

  <!-- Token de seguridad para poder crear un nuevo registro -->
  {% csrf_token %}
<table style="width:100%">
  {{ form.as_table }}
</table>
<center>
  <button type="submit" class="btn btn-primary">Guardar</button>
  <a href="{% url 'palapp:lispagt' %}" type="submit" class="btn btn-primary">Cancelar</a>
</center>

</form>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</div>
{% endblock %}

palapp/templates/palapp/edtra.html
{% extends "palapp/base.html" %}

 {% load static %} <!-- Cargar URL raíz -->

 {% load widget_tweaks %}

{% block content %}

<p style="background-color: green; color: #ffffff; font-weight: bold; font-size: x-large"> GESTION DE VENTAS </p>

<style>
    .cuerpo {
        margin-left: 40px;
        margin-right: 40px;
    }

</style>
<div id>
  <div class="cuerpo">

<form method="post" enctype="multipart/form-data">

  <!-- Token de seguridad para poder crear un nuevo registro -->
  {% csrf_token %}
<table style="width:100%">
  {{ form.as_table }}
</table>
  <center>
  <button type="submit" class="btn btn-primary">Guardar</button>
  <a href="{% url 'palapp:tralist' %}" type="submit" class="btn btn-primary">Cancelar</a>
</center>

</form>
</div>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</div>
{% endblock %}